CREATE TABLE IF NOT EXISTS clientes (
    id_cliente INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome_cliente VARCHAR(150) NOT NULL,
    telefone_contato VARCHAR(20) NOT NULL,
    cpf_cnpj VARCHAR(14) NULL,
    endereco VARCHAR(255) NULL,
    email_contato VARCHAR(150) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT chk_clientes_cpf_cnpj_len CHECK (cpf_cnpj IS NULL OR CHAR_LENGTH(cpf_cnpj) IN (11, 14))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
